name: 'Deploy OpenTelemetry'

on:
  workflow_run:
    workflows: ['*']
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: otel-deploy-job
    steps:
      - uses: plengauer/Thoth/actions/instrument/deploy@v5.21.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: '${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}'
          OTEL_EXPORTER_OTLP_HEADERS: '${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}'
        with:
          github_token: '${{ secrets.DEPLOY_OBSERVABILITY_TOKEN }}' # TODO configure a token that has permissions to push contents and open pull requests
